- defaults:
    link:
      create: true
      relink: true

- shell:
    - ["git submodule sync --quiet --recursive", "Sync submodules"]
    - ["git submodule update --init --recursive", "Installing submodules"]

- create:
    ~/.ssh:
      mode: 0700

- clean: ['~']

- clean:
    ~/.config:
      recursive: true

- link:
    # starship
    ~/.config/starship/:
      glob: true
      path: config/starship/*
      force: true
      create: true
    # General config
    ~/:
      glob: true
      path: config/general/.*
      relink: true
      exclude: [ "config/general/.gitignore*" ]
    ~/.gitconfig:
      path: config/general/.gitconfig
      force: true
      create: true
    ~/.fdignore:
      path: config/general/.gitignore_global
      force: true
      create: true