"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """
[](fg:color_gray)\
$os\
[](fg:color_blue bg:color_gray)\
$directory\
[](fg:color_blue bg:color_gray)\
$git_branch\
$git_status\
$git_commit\
[](fg:color_gray bg:color_dark_gray)\
$dart\
$golang\
$java\
$nodejs\
$php\
$python\
$rust\
$terraform\
$package\
[](fg:color_dark_gray)\
$character"""

palette = 'neo_rapture'

[palettes.neo_rapture]
color_blue = '#1d99f3'
color_bright_blue = '#03edf9'
color_red = '#fe4450'
color_gray= '#394260'
color_light_gray = '#e3e5e5'
color_dark_gray = '#212736'
color_green = '#72f1b8'
color_yellow = '#fede5d'

[character]
success_symbol = "[ ❯](color_bright_blue)"
error_symbol = "[ ](color_red)"

[os]
format = "[$symbol]($style)"
style = "bg:color_gray fg:color_blue"
disabled = false

[os.symbols]
Android = " "
Arch = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
Linux = " "
Macos = " "
Manjaro = " "
NixOS = " "
Raspbian = " "
RockyLinux = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[directory]
style = "fg:color_light_gray bg:color_blue"
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"
use_os_path_sep = false
fish_style_pwd_dir_length=1

[git_branch]
symbol = ""
style = "fg:color_blue bg:color_gray"
format = '[ $symbol $branch(:$remote_branch)]($style)'
only_attached=true

[git_status]
style = "fg:color_blue bg:color_gray"
format = '[($all_status$ahead_behind )]($style)'
conflicted = " [ ${count}](fg:color_red bg:color_gray)"
stashed = " [@${count}](fg:color_yellow bg:color_gray)"
deleted = " [-${count}](fg:color_red bg:color_gray)"
renamed = " [»${count}](fg:color_green bg:color_gray)"
modified = " [!${count}](fg:color_yellow bg:color_gray)"
# typechanged = ""
staged = " [+${count}](fg:color_green bg:color_gray)"
untracked = " [?${count}](fg:color_yellow bg:color_gray)"

ahead = ' ⇡${count}'
diverged = ' ⇡${ahead_count}⇣${behind_count}'
behind = ' ⇣${count}'

[git_commit]
style = "fg:color_blue bg:color_gray"
format = "[ @$hash $tag]($style)"
only_detached=true
disabled=false
tag_disabled=false
tag_symbol = " "

[nodejs]
symbol = ""
style = "bg:color_dark_gray"
format = '[[ $symbol ($version) ](fg:#87c332 bg:color_dark_gray)]($style)'

[rust]
symbol = ""
style = "bg:color_dark_gray"
format = '[[ $symbol ($version) ](fg:#ff491b bg:color_dark_gray)]($style)'

[golang]
symbol = ""
style = "bg:color_dark_gray"
format = '[[ $symbol ($version) ](fg:#4fd7e3 bg:color_dark_gray)]($style)'

[php]
symbol = " "
style = "bg:color_dark_gray"
format = '[[ $symbol ($version) ](fg:#943b98 bg:color_dark_gray)]($style)'

[python]
symbol = " "
style = "bg:color_dark_gray"
format = '[[ $symbol ($version) ](fg:#ffd252 bg:color_dark_gray)]($style)'

[dart]
symbol = " "
style = "bg:color_dark_gray"
format = '[[ $symbol ($version) ](fg:#00b9f1 bg:color_dark_gray)]($style)'

[java]
symbol = " "
style = "bg:color_dark_gray"
format = '[[ $symbol ($version) ](fg:#ff9637 bg:color_dark_gray)]($style)'

[terraform]
symbol = "󱁢 "
style = "bg:color_dark_gray"
format = '[[ $symbol ($version) ](fg:#574ce3 bg:color_dark_gray)]($style)'

[package]
symbol = " "
style = "bg:color_dark_gray"
format = '[](fg:color_dark_gray bg:color_blue)[[ $symbol($version) ](fg:color_dark_gray bg:color_blue)]($style)[](fg:color_blue bg:color_dark_gray)'
