@echo off
setlocal EnableExtensions DisableDelayedExpansion

if "%~1"=="" goto usage

rem Marshal arguments for the AllSigned signer bridge.
set "DOTFILES_PS_SCRIPT=%~1"
set "DOTFILES_PS_BRIDGE_DIR=%~dp0"
set "DOTFILES_PS_ARG1=%~2"
set "DOTFILES_PS_ARG2=%~3"
set "DOTFILES_PS_ARG3=%~4"
set "DOTFILES_PS_ARG4=%~5"
set "DOTFILES_PS_ARG5=%~6"
set "DOTFILES_PS_ARG6=%~7"
set "DOTFILES_PS_ARG7=%~8"
set "DOTFILES_PS_ARG8=%~9"
set "DOTFILES_PS_ARGC=0"
if defined DOTFILES_PS_ARG1 set "DOTFILES_PS_ARGC=1"
if defined DOTFILES_PS_ARG2 set "DOTFILES_PS_ARGC=2"
if defined DOTFILES_PS_ARG3 set "DOTFILES_PS_ARGC=3"
if defined DOTFILES_PS_ARG4 set "DOTFILES_PS_ARGC=4"
if defined DOTFILES_PS_ARG5 set "DOTFILES_PS_ARGC=5"
if defined DOTFILES_PS_ARG6 set "DOTFILES_PS_ARGC=6"
if defined DOTFILES_PS_ARG7 set "DOTFILES_PS_ARGC=7"
if defined DOTFILES_PS_ARG8 set "DOTFILES_PS_ARGC=8"

where pwsh.exe >nul 2>&1
if errorlevel 1 goto missing_pwsh

rem Probe PowerShell 7 with a harmless unsigned script. If it runs, execute the
rem target directly and avoid certificate/signing work entirely.
set "DOTFILES_PS_PROBE=%TEMP%\dotfiles-pwsh-probe-%RANDOM%-%RANDOM%.ps1"
> "%DOTFILES_PS_PROBE%" echo exit 0
pwsh.exe -NoProfile -File "%DOTFILES_PS_PROBE%" >nul 2>&1
set "DOTFILES_PS_PROBE_EXIT=%ERRORLEVEL%"
del /q "%DOTFILES_PS_PROBE%" >nul 2>&1
if "%DOTFILES_PS_PROBE_EXIT%"=="0" goto run_direct

if not exist "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" goto missing_windows_powershell
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwB0AG8AcAAnAAoAJABzAD0AJABlAG4AdgA6AEQATwBUAEYASQBMAEUAUwBfAFAAUwBfAFMAQwBSAEkAUABUAAoAJABhAD0AQAAoACkACgBmAG8AcgAoACQAaQA9ADEAOwAkAGkALQBsAGUAWwBpAG4AdABdACQAZQBuAHYAOgBEAE8AVABGAEkATABFAFMAXwBQAFMAXwBBAFIARwBDADsAJABpACsAKwApAHsAJABhACsAPQBbAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABdADoAOgBHAGUAdABFAG4AdgBpAHIAbwBuAG0AZQBuAHQAVgBhAHIAaQBhAGIAbABlACgAIgBEAE8AVABGAEkATABFAFMAXwBQAFMAXwBBAFIARwAkAGkAIgApAH0ACgAkAHQAPQAkAG4AdQBsAGwACgAkAGYAPQAkAGYAYQBsAHMAZQAKAHQAcgB5AHsACgAgAGkAZgAoACEAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABzACAALQBQAGEAdABoAFQAeQBwAGUAIABMAGUAYQBmACkAKQB7AHQAaAByAG8AdwAgACIAUABvAHcAZQByAFMAaABlAGwAbAAgAHMAYwByAGkAcAB0ACAAbgBvAHQAIABmAG8AdQBuAGQAOgAgACQAcwAiAH0ACgAgACQAcAB3AD0AKABHAGUAdAAtAEMAbwBtAG0AYQBuAGQAIABwAHcAcwBoAC4AZQB4AGUAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAdABvAHAAKQAuAFMAbwB1AHIAYwBlAAoAIAAkAGgAPQBKAG8AaQBuAC0AUABhAHQAaAAgACQAZQBuAHYAOgBEAE8AVABGAEkATABFAFMAXwBQAFMAXwBCAFIASQBEAEcARQBfAEQASQBSACAAJwBzAGkAZwBuAGkAbgBnAC4AcABzADEAJwAKACAAaQBmACgAIQAoAFQAZQBzAHQALQBQAGEAdABoACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAGgAIAAtAFAAYQB0AGgAVAB5AHAAZQAgAEwAZQBhAGYAKQApAHsAdABoAHIAbwB3ACAAIgBTAGkAZwBuAGkAbgBnACAAaABlAGwAcABlAHIAIABuAG8AdAAgAGYAbwB1AG4AZAA6ACAAJABoACIAfQAKACAAJABlAG4AdgA6AEQATwBUAEYASQBMAEUAUwBfAFMASQBHAE4ASQBOAEcAXwBSAEUAUQBVAEkAUgBFAEQAPQAnADEAJwAKACAAJABzAGIAPQBbAHMAYwByAGkAcAB0AGIAbABvAGMAawBdADoAOgBDAHIAZQBhAHQAZQAoACgARwBlAHQALQBDAG8AbgB0AGUAbgB0ACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAGgAIAAtAFIAYQB3ACkAKQAKACAAaQBmACgAWwBJAE8ALgBQAGEAdABoAF0AOgA6AEcAZQB0AEYAaQBsAGUATgBhAG0AZQAoACQAcwApAC0AaQBlAHEAIAAnAHMAaQBnAG4AaQBuAGcALgBwAHMAMQAnACkAewAKACAAIABpAGYAKAAoACQAYQAuAEMAbwB1AG4AdAAlADIAKQAtAG4AZQAwACkAewB0AGgAcgBvAHcAIAAnAEkAbgB2AGEAbABpAGQAIABzAGkAZwBuAGkAbgBnACAAaABlAGwAcABlAHIAIABhAHIAZwB1AG0AZQBuAHQAcwAnAH0ACgAgACAAJABhAGMAdABpAG8AbgA9ACQAbgB1AGwAbAAKACAAIAAkAHAAYQB0AGgAPQAkAG4AdQBsAGwACgAgACAAJABtAG8AZAB1AGwAZQA9ACQAbgB1AGwAbAAKACAAIABmAG8AcgAoACQAaQA9ADAAOwAkAGkALQBsAHQAJABhAC4AQwBvAHUAbgB0ADsAJABpACsAPQAyACkAewAKACAAIAAgAHMAdwBpAHQAYwBoACgAJABhAFsAJABpAF0AKQB7AAoAIAAgACAAIAAnAC0AQQBjAHQAaQBvAG4AJwB7ACQAYQBjAHQAaQBvAG4APQAkAGEAWwAkAGkAKwAxAF0AfQAKACAAIAAgACAAJwAtAFAAYQB0AGgAJwB7ACQAcABhAHQAaAA9ACQAYQBbACQAaQArADEAXQB9AAoAIAAgACAAIAAnAC0ATQBvAGQAdQBsAGUATgBhAG0AZQAnAHsAJABtAG8AZAB1AGwAZQA9ACQAYQBbACQAaQArADEAXQB9AAoAIAAgACAAIABkAGUAZgBhAHUAbAB0AHsAdABoAHIAbwB3ACAAIgBVAG4AcwB1AHAAcABvAHIAdABlAGQAIABzAGkAZwBuAGkAbgBnACAAaABlAGwAcABlAHIAIABhAHIAZwB1AG0AZQBuAHQAOgAgACQAKAAkAGEAWwAkAGkAXQApACIAfQAKACAAIAAgAH0ACgAgACAAfQAKACAAIABpAGYAKAAkAGEAYwB0AGkAbwBuAC0AZQBxACcAUAByAG8AdABlAGMAdABGAGkAbABlAHMAJwApAHsACgAgACAAIABpAGYAKAAhACQAcABhAHQAaAApAHsAdABoAHIAbwB3ACAAJwBQAHIAbwB0AGUAYwB0AEYAaQBsAGUAcwAgAHIAZQBxAHUAaQByAGUAcwAgAC0AUABhAHQAaAAnAH0ACgAgACAAIAAmACAAJABzAGIAIAAtAEEAYwB0AGkAbwBuACAAUAByAG8AdABlAGMAdABGAGkAbABlAHMAIAAtAFAAYQB0AGgAIAAkAHAAYQB0AGgACgAgACAAfQBlAGwAcwBlAGkAZgAoACQAYQBjAHQAaQBvAG4ALQBlAHEAJwBQAHIAbwB0AGUAYwB0AE0AbwBkAHUAbABlACcAKQB7AAoAIAAgACAAaQBmACgAIQAkAG0AbwBkAHUAbABlACkAewB0AGgAcgBvAHcAIAAnAFAAcgBvAHQAZQBjAHQATQBvAGQAdQBsAGUAIAByAGUAcQB1AGkAcgBlAHMAIAAtAE0AbwBkAHUAbABlAE4AYQBtAGUAJwB9AAoAIAAgACAAJgAgACQAcwBiACAALQBBAGMAdABpAG8AbgAgAFAAcgBvAHQAZQBjAHQATQBvAGQAdQBsAGUAIAAtAE0AbwBkAHUAbABlAE4AYQBtAGUAIAAkAG0AbwBkAHUAbABlAAoAIAAgAH0AZQBsAHMAZQB7AHQAaAByAG8AdwAgACIAVQBuAHMAdQBwAHAAbwByAHQAZQBkACAAcwBpAGcAbgBpAG4AZwAgAGgAZQBsAHAAZQByACAAYQBjAHQAaQBvAG4AOgAgACQAYQBjAHQAaQBvAG4AIgB9AAoAIAB9AGUAbABzAGUAewAKACAAIAAkAHQAPQBbAEkATwAuAFAAYQB0AGgAXQA6ADoAQwBoAGEAbgBnAGUARQB4AHQAZQBuAHMAaQBvAG4AKABbAEkATwAuAFAAYQB0AGgAXQA6ADoARwBlAHQAVABlAG0AcABGAGkAbABlAE4AYQBtAGUAKAApACwAJwAuAHAAcwAxACcAKQAKACAAIABDAG8AcAB5AC0ASQB0AGUAbQAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABzACAALQBEAGUAcwB0AGkAbgBhAHQAaQBvAG4AIAAkAHQAIAAtAEYAbwByAGMAZQAKACAAIAAmACAAJABzAGIAIAAtAEEAYwB0AGkAbwBuACAAUAByAG8AdABlAGMAdABGAGkAbABlAHMAIAAtAFAAYQB0AGgAIAAkAHQACgAgACAAJgAgACQAcAB3ACAALQBOAG8AUAByAG8AZgBpAGwAZQAgAC0ARgBpAGwAZQAgACQAdAAgAEAAYQAKACAAIABpAGYAKAAkAEwAQQBTAFQARQBYAEkAVABDAE8ARABFAC0AbgBlADAAKQB7ACQAZgA9ACQAdAByAHUAZQB9AAoAIAB9AAoAfQBjAGEAdABjAGgAewBXAHIAaQB0AGUALQBFAHIAcgBvAHIAIAAkAF8AOwAkAGYAPQAkAHQAcgB1AGUAfQAKAGYAaQBuAGEAbABsAHkAewAKACAAaQBmACgAJAB0ACkAewBSAGUAbQBvAHYAZQAtAEkAdABlAG0AIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQAdAAgAC0ARgBvAHIAYwBlACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlAH0ACgAgAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgAEUAbgB2ADoARABPAFQARgBJAEwARQBTAF8AUwBJAEcATgBJAE4ARwBfAFIARQBRAFUASQBSAEUARAAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAKAH0ACgBpAGYAKAAkAGYAKQB7AGUAeABpAHQAIAAxAH0ACgA=
exit /b %ERRORLEVEL%

:run_direct
if "%DOTFILES_PS_ARGC%"=="0" goto run_0
if "%DOTFILES_PS_ARGC%"=="1" goto run_1
if "%DOTFILES_PS_ARGC%"=="2" goto run_2
if "%DOTFILES_PS_ARGC%"=="3" goto run_3
if "%DOTFILES_PS_ARGC%"=="4" goto run_4
if "%DOTFILES_PS_ARGC%"=="5" goto run_5
if "%DOTFILES_PS_ARGC%"=="6" goto run_6
if "%DOTFILES_PS_ARGC%"=="7" goto run_7
if "%DOTFILES_PS_ARGC%"=="8" goto run_8
exit /b 2

:run_0
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%"
exit /b %ERRORLEVEL%

:run_1
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%"
exit /b %ERRORLEVEL%

:run_2
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%"
exit /b %ERRORLEVEL%

:run_3
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%"
exit /b %ERRORLEVEL%

:run_4
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%" "%DOTFILES_PS_ARG4%"
exit /b %ERRORLEVEL%

:run_5
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%" "%DOTFILES_PS_ARG4%" "%DOTFILES_PS_ARG5%"
exit /b %ERRORLEVEL%

:run_6
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%" "%DOTFILES_PS_ARG4%" "%DOTFILES_PS_ARG5%" "%DOTFILES_PS_ARG6%"
exit /b %ERRORLEVEL%

:run_7
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%" "%DOTFILES_PS_ARG4%" "%DOTFILES_PS_ARG5%" "%DOTFILES_PS_ARG6%" "%DOTFILES_PS_ARG7%"
exit /b %ERRORLEVEL%

:run_8
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%" "%DOTFILES_PS_ARG4%" "%DOTFILES_PS_ARG5%" "%DOTFILES_PS_ARG6%" "%DOTFILES_PS_ARG7%" "%DOTFILES_PS_ARG8%"
exit /b %ERRORLEVEL%

:usage
echo Usage: %~nx0 script.ps1 [arguments...] 1>&2
exit /b 2

:missing_pwsh
echo PowerShell 7 (pwsh.exe) is required. 1>&2
exit /b 1

:missing_windows_powershell
echo Windows PowerShell is required to bootstrap Authenticode signing under AllSigned. 1>&2
exit /b 1
