@echo off
setlocal EnableExtensions DisableDelayedExpansion

if "%~1"=="" goto usage

rem Marshal arguments for the AllSigned signer bridge.
set "DOTFILES_PS_SCRIPT=%~1"
set "DOTFILES_PS_BRIDGE_DIR=%~dp0"
set "DOTFILES_PS_ARG1=%~2"
set "DOTFILES_PS_ARG2=%~3"
set "DOTFILES_PS_ARG3=%~4"
set "DOTFILES_PS_ARG4=%~5"
set "DOTFILES_PS_ARG5=%~6"
set "DOTFILES_PS_ARG6=%~7"
set "DOTFILES_PS_ARG7=%~8"
set "DOTFILES_PS_ARG8=%~9"
set "DOTFILES_PS_ARGC=0"
if defined DOTFILES_PS_ARG1 set "DOTFILES_PS_ARGC=1"
if defined DOTFILES_PS_ARG2 set "DOTFILES_PS_ARGC=2"
if defined DOTFILES_PS_ARG3 set "DOTFILES_PS_ARGC=3"
if defined DOTFILES_PS_ARG4 set "DOTFILES_PS_ARGC=4"
if defined DOTFILES_PS_ARG5 set "DOTFILES_PS_ARGC=5"
if defined DOTFILES_PS_ARG6 set "DOTFILES_PS_ARGC=6"
if defined DOTFILES_PS_ARG7 set "DOTFILES_PS_ARGC=7"
if defined DOTFILES_PS_ARG8 set "DOTFILES_PS_ARGC=8"

where pwsh.exe >nul 2>&1
if errorlevel 1 goto missing_pwsh

rem Probe PowerShell 7 with a harmless unsigned script. If it runs, execute the
rem target directly and avoid certificate/signing work entirely.
set "DOTFILES_PS_PROBE=%TEMP%\dotfiles-pwsh-probe-%RANDOM%-%RANDOM%.ps1"
> "%DOTFILES_PS_PROBE%" echo exit 0
pwsh.exe -NoProfile -File "%DOTFILES_PS_PROBE%" >nul 2>&1
set "DOTFILES_PS_PROBE_EXIT=%ERRORLEVEL%"
del /q "%DOTFILES_PS_PROBE%" >nul 2>&1
if "%DOTFILES_PS_PROBE_EXIT%"=="0" goto run_direct

if not exist "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" goto missing_windows_powershell
rem A nested bridge can inherit PowerShell 7's PSModulePath. Restore the inbox
rem Windows PowerShell module roots before starting the signing host.
set "PSModulePath=%USERPROFILE%\Documents\WindowsPowerShell\Modules;%ProgramFiles%\WindowsPowerShell\Modules;%SystemRoot%\System32\WindowsPowerShell\v1.0\Modules"
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwB0AG8AcAAnAAoAJABzAD0AJABlAG4AdgA6AEQATwBUAEYASQBMAEUAUwBfAFAAUwBfAFMAQwBSAEkAUABUAAoAJABhAD0AQAAoACkACgBmAG8AcgAoACQAaQA9ADEAOwAkAGkALQBsAGUAWwBpAG4AdABdACQAZQBuAHYAOgBEAE8AVABGAEkATABFAFMAXwBQAFMAXwBBAFIARwBDADsAJABpACsAKwApAHsAJABhACsAPQBbAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABdADoAOgBHAGUAdABFAG4AdgBpAHIAbwBuAG0AZQBuAHQAVgBhAHIAaQBhAGIAbABlACgAIgBEAE8AVABGAEkATABFAFMAXwBQAFMAXwBBAFIARwAkAGkAIgApAH0ACgAkAHQAPQAkAG4AdQBsAGwACgAkAGYAPQAkAGYAYQBsAHMAZQAKAHQAcgB5AHsACgAgAGkAZgAoACEAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABzACAALQBQAGEAdABoAFQAeQBwAGUAIABMAGUAYQBmACkAKQB7AHQAaAByAG8AdwAgACIAUABvAHcAZQByAFMAaABlAGwAbAAgAHMAYwByAGkAcAB0ACAAbgBvAHQAIABmAG8AdQBuAGQAOgAgACQAcwAiAH0ACgAgACQAcAB3AD0AKABHAGUAdAAtAEMAbwBtAG0AYQBuAGQAIABwAHcAcwBoAC4AZQB4AGUAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAdABvAHAAKQAuAFMAbwB1AHIAYwBlAAoAIAAkAHAAcwA9AEoAbwBpAG4ALQBQAGEAdABoACAAJABlAG4AdgA6AFMAeQBzAHQAZQBtAFIAbwBvAHQAIAAnAFMAeQBzAHQAZQBtADMAMgBcAFcAaQBuAGQAbwB3AHMAUABvAHcAZQByAFMAaABlAGwAbABcAHYAMQAuADAAXABwAG8AdwBlAHIAcwBoAGUAbABsAC4AZQB4AGUAJwAKACAAaQBmACgAIQAoAFQAZQBzAHQALQBQAGEAdABoACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAHAAcwAgAC0AUABhAHQAaABUAHkAcABlACAATABlAGEAZgApACkAewB0AGgAcgBvAHcAIAAiAFcAaQBuAGQAbwB3AHMAIABQAG8AdwBlAHIAUwBoAGUAbABsACAAbgBvAHQAIABmAG8AdQBuAGQAOgAgACQAcABzACIAfQAKACAAJABoAD0ASgBvAGkAbgAtAFAAYQB0AGgAIAAkAGUAbgB2ADoARABPAFQARgBJAEwARQBTAF8AUABTAF8AQgBSAEkARABHAEUAXwBEAEkAUgAgACcAcwBpAGcAbgBpAG4AZwAuAHAAcwAxACcACgAgAGkAZgAoACEAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABoACAALQBQAGEAdABoAFQAeQBwAGUAIABMAGUAYQBmACkAKQB7AHQAaAByAG8AdwAgACIAUwBpAGcAbgBpAG4AZwAgAGgAZQBsAHAAZQByACAAbgBvAHQAIABmAG8AdQBuAGQAOgAgACQAaAAiAH0ACgAgACQAZQBuAHYAOgBEAE8AVABGAEkATABFAFMAXwBTAEkARwBOAEkATgBHAF8AUgBFAFEAVQBJAFIARQBEAD0AJwAxACcACgAgAGkAZgAoAFsASQBPAC4AUABhAHQAaABdADoAOgBHAGUAdABGAGkAbABlAE4AYQBtAGUAKAAkAHMAKQAtAGkAZQBxACAAJwBzAGkAZwBuAGkAbgBnAC4AcABzADEAJwApAHsACgAgACAAJgAgACQAcABzACAALQBOAG8AUAByAG8AZgBpAGwAZQAgAC0ARgBpAGwAZQAgACQAaAAgAEAAYQAKACAAIABpAGYAKAAkAEwAQQBTAFQARQBYAEkAVABDAE8ARABFAC0AbgBlADAAKQB7ACQAZgA9ACQAdAByAHUAZQB9AAoAIAB9AGUAbABzAGUAewAKACAAIAAkAHQAPQBbAEkATwAuAFAAYQB0AGgAXQA6ADoAQwBoAGEAbgBnAGUARQB4AHQAZQBuAHMAaQBvAG4AKABbAEkATwAuAFAAYQB0AGgAXQA6ADoARwBlAHQAVABlAG0AcABGAGkAbABlAE4AYQBtAGUAKAApACwAJwAuAHAAcwAxACcAKQAKACAAIABDAG8AcAB5AC0ASQB0AGUAbQAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABzACAALQBEAGUAcwB0AGkAbgBhAHQAaQBvAG4AIAAkAHQAIAAtAEYAbwByAGMAZQAKACAAIAAmACAAJABwAHMAIAAtAE4AbwBQAHIAbwBmAGkAbABlACAALQBGAGkAbABlACAAJABoACAALQBBAGMAdABpAG8AbgAgAFAAcgBvAHQAZQBjAHQARgBpAGwAZQBzACAALQBQAGEAdABoACAAJAB0AAoAIAAgAGkAZgAoACQATABBAFMAVABFAFgASQBUAEMATwBEAEUALQBuAGUAMAApAHsAdABoAHIAbwB3ACAAIgBTAGkAZwBuAGkAbgBnACAAaABlAGwAcABlAHIAIABmAGEAaQBsAGUAZAAgAHcAaQB0AGgAIABlAHgAaQB0ACAAYwBvAGQAZQAgACQATABBAFMAVABFAFgASQBUAEMATwBEAEUAIgB9AAoAIAAgACYAIAAkAHAAdwAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAEYAaQBsAGUAIAAkAHQAIABAAGEACgAgACAAaQBmACgAJABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQAtAG4AZQAwACkAewAkAGYAPQAkAHQAcgB1AGUAfQAKACAAfQAKAH0AYwBhAHQAYwBoAHsAVwByAGkAdABlAC0ARQByAHIAbwByACAAJABfADsAJABmAD0AJAB0AHIAdQBlAH0ACgBmAGkAbgBhAGwAbAB5AHsACgAgAGkAZgAoACQAdAApAHsAUgBlAG0AbwB2AGUALQBJAHQAZQBtACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAHQAIAAtAEYAbwByAGMAZQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQB9AAoAIABSAGUAbQBvAHYAZQAtAEkAdABlAG0AIABFAG4AdgA6AEQATwBUAEYASQBMAEUAUwBfAFMASQBHAE4ASQBOAEcAXwBSAEUAUQBVAEkAUgBFAEQAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUACgB9AAoAaQBmACgAJABmACkAewBlAHgAaQB0ACAAMQB9AAoA
exit /b %ERRORLEVEL%

:run_direct
if "%DOTFILES_PS_ARGC%"=="0" goto run_0
if "%DOTFILES_PS_ARGC%"=="1" goto run_1
if "%DOTFILES_PS_ARGC%"=="2" goto run_2
if "%DOTFILES_PS_ARGC%"=="3" goto run_3
if "%DOTFILES_PS_ARGC%"=="4" goto run_4
if "%DOTFILES_PS_ARGC%"=="5" goto run_5
if "%DOTFILES_PS_ARGC%"=="6" goto run_6
if "%DOTFILES_PS_ARGC%"=="7" goto run_7
if "%DOTFILES_PS_ARGC%"=="8" goto run_8
exit /b 2

:run_0
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%"
exit /b %ERRORLEVEL%

:run_1
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%"
exit /b %ERRORLEVEL%

:run_2
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%"
exit /b %ERRORLEVEL%

:run_3
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%"
exit /b %ERRORLEVEL%

:run_4
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%" "%DOTFILES_PS_ARG4%"
exit /b %ERRORLEVEL%

:run_5
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%" "%DOTFILES_PS_ARG4%" "%DOTFILES_PS_ARG5%"
exit /b %ERRORLEVEL%

:run_6
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%" "%DOTFILES_PS_ARG4%" "%DOTFILES_PS_ARG5%" "%DOTFILES_PS_ARG6%"
exit /b %ERRORLEVEL%

:run_7
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%" "%DOTFILES_PS_ARG4%" "%DOTFILES_PS_ARG5%" "%DOTFILES_PS_ARG6%" "%DOTFILES_PS_ARG7%"
exit /b %ERRORLEVEL%

:run_8
pwsh.exe -NoProfile -File "%DOTFILES_PS_SCRIPT%" "%DOTFILES_PS_ARG1%" "%DOTFILES_PS_ARG2%" "%DOTFILES_PS_ARG3%" "%DOTFILES_PS_ARG4%" "%DOTFILES_PS_ARG5%" "%DOTFILES_PS_ARG6%" "%DOTFILES_PS_ARG7%" "%DOTFILES_PS_ARG8%"
exit /b %ERRORLEVEL%

:usage
echo Usage: %~nx0 script.ps1 [arguments...] 1>&2
exit /b 2

:missing_pwsh
echo PowerShell 7 (pwsh.exe) is required. 1>&2
exit /b 1

:missing_windows_powershell
echo Windows PowerShell is required to bootstrap Authenticode signing under AllSigned. 1>&2
exit /b 1
